- name: nginx install & run
  hosts: frontend1
  become: yes # sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package: # If we use package module it will work both dnf and apt
      name: nginx
      state: present
  - name: start and enable nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  