- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - files.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
    #vars refernce should be surrounded by ""
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"