- name: conditions demo-1
  hosts: local
  connection: local
  vars:
    NUMBER: 78
  tasks:
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than or equal to 100"
    when: NUMBER <= 100

  - name: print if the number is greater than 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is greater than 100"
    when: NUMBER > 100

- name: conditions demo-2
  hosts: local
  connection: local
  vars:
    NUMBER: 102
  tasks:
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than or equal to 100"
    when: NUMBER <= 100

  - name: print if the number is greater than 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is greater than 100"
    when: NUMBER > 100