- name: user creaion
  hosts: localhost
  connection: local
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshob
    register: output
    ignore_errors: true
  
  - name: create user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0

  - name: user already exists
    ansible.builtin.debug:
      msg: "user already exists"
    when: output.rc == 0