- name: instal nginx
  hosts: dynamic_ansible
  become: yes
  tasks: 
  - name: install nginxa
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      